export const START = 'start';
export const STOP = 'stop';
export const CONFIG = 'config';
export const RECORDING = 'recording';
export const DEBUG = 'debug';
export const LOG = 'log';
export const ERROR = 'error';
export const FAIL = 'fail';
export const RTMP = 'rtmp';
export const RECONNECT = 'reconnect';
export const STREAM_DISCONNECT = 'stream_disconnect';
export const BINARY_STREAM = 'binary_stream';
export const DANMU_OPTION = 'danmu_option';
export const DANMU_ERROR = 'danmu_error';

export const SOCKET_SUCCESS = '建立socket连接成功';
export const SOCKET_FAIL = '建立socket连接失败';
export const TAB_VIDEO_STREAM_SUCCESS = '获取标签视频流成功';
export const TAB_VIDEO_STREAM_FAIL = '无法获取标签视频流，请重试！';
export const RECORDER_SUCCESS = '录制器启动成功';
export const RECORDER_FAIL = '无法录制标签的视频流，请重试！';
export const PUSH_STREAM_ING = '正在推流中...';
export const CAN_NOT_FIND_TAB = '未获取到当前激活的标签';
export const RTMP_ERROR = '请输入正确的rtmp推流地址';
export const STREAM_NAME_ERROR = '请输入正确的直播码';
export const SOCKET_ERROR = '请输入正确的中转地址';
export const LIVE_ROOM_ERROR = '不是有效的 Bilibili 直播间地址';
export const OPEN_SUCCESS = '打开直播间页面成功';
export const DANMU_ING = '正在获取弹幕接口...';
export const DANMU_SUCCESS = '获取弹幕接口成功';
export const DANMU_FAIL = '获取弹幕接口失败';
export const CURRENT_PAGE = '当前页面';
export const PUSH_STREAM_END = '已停止推流...';
export const RECONNECT_INFO = '自动重连中：';
export const INJECTED_SUCCESS = '注入文件：';

export const DEFAULT_SOCKET = 'http://localhost:8080';
export const DEFAULT_RESOLUTION = 720;
export const DEFAULT_VIDEO_BITSPER = 2500000;
export const DEFAULT_AUDIO_BITSPER = 128000;
export const MIME_TYPE = 'video/webm; codecs="h264, opus"';
export const RECONNECT_TIME = 100;
export const MAX_DANMU = 50;

export const REG_RTMP = /^rtmp:\/\/.+/i;
export const REG_HTTP = /^https?:\/\/.+/i;
export const REG_LIVE = /^https?:\/\/live\.bilibili\.com/i;
export const REG_FUNCTION = /^function\s*([\w$]*)\s*\(([\w\s,$]*)\)\s*\{([\w\W\s\S]*)\}$/;
